-- Useful keymaps
vim.keymap.set('n', '\\', ':split<CR>', { silent = true, desc = 'Horizontal Split' })

vim.keymap.set('n', '<leader>K', ':split<CR>', { silent = true, desc = 'Horizontal Split' })
vim.keymap.set('n', '<leader>k', ':vsplit<CR>', { silent = true, desc = 'Vertical Split' })
vim.keymap.set('n', '<leader>\\', function()
  vim.fn.system('fish -c "yazi_hsplit ' .. vim.fn.expand '%:p' .. '"')
end, { silent = true, desc = 'Yazi - Vertical Split' })
vim.keymap.set('n', '|', ':vsplit<CR>', { silent = true, desc = 'Vertical Split' })
vim.keymap.set('n', '<leader>|', function()
  vim.fn.system('fish -c "yazi_vsplit ' .. vim.fn.expand '%:p' .. '"')
end, { silent = true, desc = 'Yazi - Vertical Split' })
vim.keymap.set('n', '<leader>I', function()
  vim.fn.system('fish -c "yazi_new_tab ' .. vim.fn.expand '%:p' .. '"')
end, { silent = true, desc = 'Yazi - Tab' })
